# Generated by Django 2.2.7 on 2019-11-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('psa', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('overAll', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('id', models.IntegerField()),
                ('team_flag', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
    ]
