# Generated by Django 2.2.7 on 2019-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='overAll',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='potential',
            field=models.CharField(max_length=50),
        ),
    ]
