package time;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Time.java
//  @ Date : 2019-05-수요일
//  @ Author : 
//

public class Time {
  public int Hour;
  public int Miniute;
  public int Second;
  public int Year;
  public int Month;
  public int Day;
  public boolean Alarm;
  
  Time(){
	  Hour=0;
	  Miniute=0;
	  Second=0;
	  Year=2019;
	  Month=1;
	  Day=1;
	  Alarm=false;	  
  }
  Time(int a,int b, int c){
	  
  }
  public void Timing() {
	  this.Second++;
	  if(this.Second==60) {
		  this.Miniute++;
		  this.Second=0;
	  }
	  if(this.Miniute==60) {
		  this.Miniute=0;
		  this.Hour++;
	  }
	  if(this.Hour==24)
		  this.Hour=0;
  }
  public String getTime() {
	  String a = "";
	  a+= this.Hour +"시";
	  a+= this.Miniute +"분";
	  a+= this.Second+"초\t";
	  a+= this.Year+"년";
	  a+= this.Month+"월";
	  a+= this.Day+"일";
	  return a;
  }  
  
  public void setAlarm(int hour,int minute, int second) {
	  if(!this.Alarm)
		  this.Alarm = !this.Alarm;
	  if(hour==getHour() &&minute==getMiniute() && second == getSecond() && this.Alarm) {
		  System.out.println("일어나세요");
	  }
  }
  public int getHour() {
	  return this.Hour;
  }
  
  public int getMiniute() {
	  return this.Miniute;
  }
  
  public int getSecond() {
	  return this.Second;
  }
  public void setHour(int Hour) {
	  this.Hour=Hour;
  }
  
  public void setMiniute( int miniute) {
	  this.Miniute=miniute;
  }
  
  public void setSecond( int second) {
	  this.Second=second;
  }
  
  public void setYear( int year) {
	  this.Year=year;
  }
  
  public void setMonth( int month) {
	  this.Month = month;
  }
  
  public void setDay( int day) {
  this.Day = day;
  }  
@Override
public String toString() {
	return "Time [Hour=" + Hour + ", Miniute=" + Miniute + ", Second=" + Second + ", Year=" + Year + ", Month=" + Month
			+ ", Day=" + Day + ", Alarm=" + Alarm +"]";
}
  
}
