# Generated by Django 2.2.7 on 2019-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191203_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
