# Generated by Django 2.2.7 on 2019-11-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('psa', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('overAll', models.CharField(max_length=50)),
                ('potential', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50)),
                ('team_flag', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('nation_flag', models.CharField(max_length=40)),
                ('position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poten.Player')),
            ],
        ),
    ]
