# Generated by Django 2.2.7 on 2019-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
